/*
Copyright 2018 Keysight Technologies

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cmt_v1alpha1 "github.com/openixia/cmt-controller/pkg/apis/cmt/v1alpha1"
	versioned "github.com/openixia/cmt-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openixia/cmt-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openixia/cmt-controller/pkg/client/listers/cmt/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ConfigMapTemplateInformer provides access to a shared informer and lister for
// ConfigMapTemplates.
type ConfigMapTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ConfigMapTemplateLister
}

type configMapTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewConfigMapTemplateInformer constructs a new informer for ConfigMapTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewConfigMapTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredConfigMapTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredConfigMapTemplateInformer constructs a new informer for ConfigMapTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredConfigMapTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CmtV1alpha1().ConfigMapTemplates(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CmtV1alpha1().ConfigMapTemplates(namespace).Watch(options)
			},
		},
		&cmt_v1alpha1.ConfigMapTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *configMapTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredConfigMapTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *configMapTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cmt_v1alpha1.ConfigMapTemplate{}, f.defaultInformer)
}

func (f *configMapTemplateInformer) Lister() v1alpha1.ConfigMapTemplateLister {
	return v1alpha1.NewConfigMapTemplateLister(f.Informer().GetIndexer())
}
