apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configmaptemplates.cmt.openixia.com
  labels:
    app: configmap-template-controller
spec:
  group: cmt.openixia.com
  version: v1alpha1
  names:
    kind: ConfigMapTemplate
    plural: configmaptemplates
  scope: Namespaced
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-bro-configmaptemplate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: configmap-template-controller
  name: cmt-config-watcher
  namespace: kube-bro-configmaptemplate
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "cmt.openixia.com"
  resources:
  - configmaptemplates
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-05-21T18:48:29Z
  labels:
    app: configmap-template-controller
  name: configmap-template-controller
  namespace: kube-bro-configmaptemplate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: configmap-template-controller
  name: cmt-config-watcher
  namespace: kube-bro-configmaptemplate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cmt-config-watcher
subjects:
- kind: ServiceAccount
  name: configmap-template-controller
  namespace: kube-bro-configmaptemplate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-bro-configmaptemplate
  name: configmap-template-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-template-controller
  template:
    metadata:
      labels:
        app: configmap-template-controller
    spec:
      containers:
        - name: controller
          image: ixiacom/kube-bro-configmaptemplate:0.2.1
          args:
            - "-stderrthreshold"
            - info
      serviceAccount: configmap-template-controller
      imagePullSecrets:
        - name: artifactory-docker-secret
